### ISSUE TITLE
example is_it_time_to_buy and sell functions

### ISSUE THREAD

**Issue by 000KeyserSoze000** [smzerehpoush/binance-spot-trading-bot#2]
Hello, congratulations.
Have you an code example for write in main.py (especially inside is_it_time_to_sell and is_it_time_to_buy functions).?
Thanks

**Comment by smzerehpoush** [comment]
hello

you can define your strategies here.

for example if rsi value is greater than or equal to 70 and heikin ashi value is positive then buy or sell asset

for some reasons i can not public my strategy (it's under test)
