### ISSUE TITLE
Binance spot trading bot from signal telegram Channel

### ISSUE THREAD

**Issue by DungPT10** [smzerehpoush/binance-spot-trading-bot#5]
Hello bro !
Can you edit your project with feature :
+ Spot trading bot , signal from telegram ,  Signal parser from this source code :  https://github.com/JuicedBakker/telegram-crypto-signal-parser .
+ user can edit any id Channel from telegram.

Thank so much !

**Comment by smzerehpoush** [comment]
Hello @DungPT10 
sorry. project goal is different.
